name: Docker

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "5.5"
          - version: "5.5-fpm"
          - version: "5.6"
          - version: "5.6-fpm"
          - version: "7.0"
          - version: "7.0-fpm"
          - version: "7.1"
          - version: "7.1-fpm"
          - version: "7.2"
          - version: "7.2-fpm"
          - version: "7.3"
          - version: "7.3-fpm"
          - version: "7.4"
          - version: "7.4-fpm"
          - version: "8.0"
          - version: "8.0-fpm"

      fail-fast: false

    name: Docker (dockette/php:${{ matrix.version }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.version  }}
          push: true
          tags: dockette/php:${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
